# Project 4: NJ tree construction

**Group 10**

Emma Réka Erdei

Martina Chabadová

Juan Nicolás Quintero Quintero

---

## Introduction
We have implemented **NJ algorithm** using numpy and a custom **Node** class to find the neighbor joining tree corresponding to a distance matrix. Everything works as expected, and our results match the provided test case (i.e. the tree from the slides).

We also ran comparisons of our method with the **QuickTree** and **Rapid NJ**, to do so, we ran the three methods in the same script using the **subprocess** library to execute QuickTree and Rapid NJ measuring the execution time of all the methods. All the experiments were run in a **A description of the of the machine (cpu, ram, os, ...) that you have used to perform the experiment**.


## Methods

To implement our solution, we use one file with helper functions, a Node class and 3 functions to perform the neighbor joining. Everything is located in the **neighbor_joining.py** file.

### Helper functions
The helper functions are:

- read_distance_matrix
- write_newick_to_file

### Node class

The node class is in charge of storing the neighbor joining tree. Each iteration of the algorithm will create a new node with 2 nodes as children. The last step of the algorithm will create a root node joining the last 3 nodes of the tree.

Additionally, they have one writting method (write_in_newick) that recursively traverses the tree and creates the newick string representing the tree.

### Neighbor Joining algorithm

We implemented the neighbor joining algorithm as seen in class, the implementation was done in python, using the **numpy** library to vectorize the operations and updates as much as possible to optimize the running time. The algorithm consist of 3 functions:


1. **neighbour_joining:** This is the main function, which starts the process. In a loop, it determines the two nodes to be joined at every step of the algorithm with the *join* function, and when there are only 3 nodes, calls the *join_last_nodes* function.

2. **join**: This function performs one step of the algorithm joining the two nodes selected by the algorithm and updating the nodes list and distance matrix

3. **join_last_nodes:** This is the last step of the algorithm, that joing the last 3 nodes of the tree and create a root node for the resulting tree.

All of these functions rely on the numpy library, calculating important quantities as the *r* vector and the *Q* matrix with vectorized operations which are more efficient than looping in python, as well as updating and replacing the distance matrix using numpy functions and masks to make it as efficient as possible.

## Experiments

### Running times

For measuring running times, we ran our implementation and the two provided programs for quicktree and rapid_nj in the machine specified in the introduction. The results are summarized in the following table:

In [9]:
import pandas as pd
times = pd.read_csv("time_experiments_results.csv", index_col = 0)
times = times.sort_values("n")
times['quicktree_vs_nj'] = times['quicktree'] / times['neighbor_joining']
times['rapidnj_vs_nj'] = times['rapid_nj'] / times['neighbor_joining']
times

,n,neighbor_joining,rapid_nj,quicktree,quicktree_vs_nj,rapidnj_vs_nj
12,89,0.002069,0.002813,0.001977,0.955530,1.359217
2,214,0.017448,0.005068,0.008522,0.488385,0.290432
7,304,0.032506,0.008845,0.017004,0.523082,0.272088
13,401,0.072712,0.022823,0.039185,0.538906,0.313888
8,494,0.127822,0.021389,0.048436,0.378930,0.167336
11,608,0.264186,0.038908,0.063953,0.242074,0.147275
0,777,0.751910,0.056630,0.129873,0.172724,0.075315
10,877,1.108167,0.073864,0.174497,0.157465,0.066654
5,1347,5.096886,0.202429,0.573789,0.112576,0.039716
3,1493,7.086102,0.212338,0.723053,0.102038,0.029965
1,1560,8.193381,0.217033,0.856093,0.104486,0.026489
9,1689,10.676561,0.276146,1.032839,0.096739,0.025865
4,1756,12.351810,0.330138,1.136007,0.091971,0.026728
6,1849,14.571806,0.321753,1.392794,0.095581,0.022081

We can clearly see that our implementation is way slower than the heuristics, as expected. We can also note that rapidnj is way faster and the preformance is significantly better as the input size increase

### Distances

After comparing the running times, we compared as well the results of the 3 methods for each of the 14 test cases. The results are summarized in the following table:

In [9]:
import pandas as pd
import matplotlib.pyplot as plt

distances = pd.read_csv("RF-distances/rf_distances.csv")
distances = distances.sort_values("n").reset_index(drop = True)
distances

       n  nj_vs_quick  nj_vs_rapid  quick_vs_rapid
0     89           16           32              30
1    214           18           52              56
2    304           12           78              78
3    401           32           86              98
4    494          208          530             532
5    608           20           12              20
6    777          208          476             494
7    877           32           42              54
8   1347            2            4               2
9   1493           34           98              92
10  1560           76          154             152
11  1689           38          104             102
12  1756           22           78              76
13  1849           98          276             280

Which are better visualized in the following plot:

We can clearly distinguish 2 cases regarding to the RF distances:
 
1. For the first case, the distance is very low independent on the pair of methods considered. This is most likely because the matrix distances were additive matrices, or close to additive matrices, yielding very similar trees for every method considered. 
2. The other case occurs when all the methods have a high distance, most likely because the matrices are not additive and the heuristic used to speedup the computation in Quicktree and Rapid NJ may choose different pairs to join as our implementation.

It is worth mentioning that when there are high differences between the methods, our implementation is closer to Rapid NJ than to QuickTree and the difference between our implementation and QuickTree is similar to the distance between QuickTree and Rapid NJ.